// src/swcc/pages/BookListPage.jsx — SWCC Henry R. Meifert Memorial Library — Book List
import { useState, useMemo } from 'react';

const CATEGORIES = [
  {
    name: 'Recently Added',
    books: [
      { title: 'Batsford Chess Openings, 1982',                        author: 'Kasparov & Keene',                              box: 10 },
      { title: '1234 Modern Endgame Studies, 1968',                    author: 'Sutherland & Lommer',                          box: 10 },
      { title: 'Modern Chess Opening Theory, 1965',                    author: 'Suetin',                                       box: 10 },
      { title: 'Attack & Counterattack in Chess, 1955',                author: 'Reinfeld',                                     box: 10 },
      { title: 'Chess Endings: Essential Knowledge, 1966',             author: 'Averbakh',                                     box: 10 },
      { title: 'Modern Art of Attack, 1988',                           author: 'Smith & Hall',                                 box: 10 },
      { title: 'An Opening Repertoire for the Attacking Player, 1976', author: 'Levy & Keene',                                 box: 10 },
      { title: 'My 60 Memorable Games, 2008 (algebraic!)',             author: 'Fischer',                                      box: 10 },
      { title: 'Sharpen Your Tactics, 1996',                           author: 'Lein & Archangelsky',                          box: 10 },
      { title: 'Pawn Structure Chess, 1995',                           author: 'Soltis',                                       box: 10 },
      { title: 'How to Defend in Chess, 2000',                         author: 'Crouch',                                       box: 10 },
      { title: 'Chess Travellers Quiz Book, 1993',                     author: 'Hodgson',                                      box: 10 },
      { title: "Jon Speelman's Chess Puzzle Book, 2008",               author: 'Speelman',                                     box: 10 },
      { title: 'Attacking Chess, The French, 2011',                    author: 'Williams',                                     box: 10 },
      { title: 'Can You Be a Positional Chess Genius?, 2002',          author: 'Dunnington',                                   box: 10 },
      { title: 'Endgame Magic, 1996',                                  author: 'Beasley & Whitworth',                          box: 10 },
      { title: 'Play the Slav, 2008',                                  author: 'Vigus',                                        box: 10 },
      { title: 'Soviet Middlegame Technique, 2010',                    author: 'Romanovsky',                                   box: 10 },
      { title: 'The Art of Positional Play, 1976',                     author: 'Reshevsky',                                    box: 10 },
      { title: 'How to Open a Chess Game, 1974',                       author: 'Evans, Gligoric, Hort, Petrosian, Portisch, Keres, Larsen', box: 10 },
      { title: 'Kings of Chess, 1966',                                 author: 'Winter',                                       box: 10 },
      { title: 'An Illustrated Dictionary of Chess, 1977',             author: 'Brace',                                       box: 10 },
      { title: 'Creative Chess, 1991',                                 author: 'Avni',                                        box: 10 },
      { title: 'How to Choose a Chess Move, 2005',                     author: 'Soltis',                                       box: 10 },
      { title: 'New in Chess Yearbook 96, 2010',                       author: 'NiC',                                          box: 10 },
      { title: 'New in Chess Yearbook 97, 2010',                       author: 'NiC',                                          box: 10 },
      { title: 'Fighting Chess with Magnus Carlsen, 2012',             author: 'Mikhalchishin & Stetsko',                      box: 10 },
      { title: 'What it Takes to Become a Chess Master, 2012',         author: 'Soltis',                                       box: 10 },
      { title: 'The Flexible French, 2008',                            author: 'Moskalenko',                                   box: 10 },
      { title: 'Mastering the Chess Openings Vol 1, 2006',             author: 'Watson',                                       box: 10 },
      { title: 'The Rossolimo Sicilian, 2011',                         author: 'Bologan',                                      box: 10 },
      { title: 'The Chess Puzzle Book 4, 2012',                        author: 'Muller & Markgraf',                            box: 10 },
      { title: 'Understanding Chess Middlegames, 2011',                author: 'Nunn',                                         box: 10 },
      { title: 'Simple Attacking Plans, 2012',                         author: 'Wilson',                                       box: 10 },
      { title: 'Better Chess for Average Players, 1996',               author: 'Harding',                                      box: 10 },
      { title: 'The Art of Planning in Chess, 2006',                   author: 'McDonald',                                     box: 10 },
      { title: 'The Veresov, 2003',                                    author: 'Davies',                                       box: 10 },
      { title: 'Test Your Positional Play, 1985',                      author: 'Bellin & Ponzetto',                            box: 10 },
      { title: 'Chess for Tigers, 2005',                               author: 'Webb',                                         box: 10 },
      { title: 'Starting Out: 1d4, 2006',                              author: 'Cox',                                          box: 10 },
      { title: 'Logical Chess Move by Move, 1998',                     author: 'Chernev',                                      box: 10 },
      { title: 'Life and Games of Mikhail Tal, 1997',                  author: 'Tal',                                          box: 10 },
      { title: 'Endgame Strategy, 1994',                               author: 'Shereshevsky',                                 box: 10 },
      { title: 'The Complete Hedgehog Vol 2, 2011',                    author: 'Shipov',                                       box: 10 },
      { title: 'Chess to Enjoy, 1978',                                 author: 'Soltis',                                       box: 11 },
      { title: 'Battles Royal of the Chessboard, 1995',                author: 'Coles',                                        box: 11 },
      { title: 'Winning Chess Traps, 1962',                            author: 'Chernev',                                      box: 11 },
      { title: "Queen's Gambit Declined 5.Bf4, 1998",                  author: 'Crouch',                                       box: 11 },
      { title: 'How to Become a Candidate Master, 1992',               author: 'Dunne',                                        box: 11 },
      { title: "How to Become a Candidate Master — Answer Guide, 1992",author: 'Dunne',                                        box: 11 },
      { title: 'Chess the Easy Way, 1942',                             author: 'Fine',                                         box: 11 },
      { title: '2c3 vs. The Sicilian and the Smith-Morra Gambit Declined, 1992', author: 'Smith',                              box: 11 },
      { title: 'How to Win Chess Games Quickly, 1956',                 author: 'Reinfeld',                                     box: 11 },
      { title: 'Simple Chess, 1978',                                   author: 'Stean',                                        box: 11 },
      { title: 'Grandmaster Chess, 1975',                              author: 'Kashdan & Acers',                              box: 11 },
      { title: 'How to Force Checkmate, 1947',                         author: 'Reinfeld',                                     box: 11 },
      { title: 'The Sicilian Accelerated Dragon, 1998',                author: 'Nielsen & Hansten',                            box: 11 },
      { title: 'Modern Ideas in Chess, 1960',                          author: 'Reti',                                         box: 11 },
      { title: 'How to Think Ahead in Chess, 1964',                    author: 'Horowitz & Reinfeld',                          box: 11 },
      { title: 'Weapons of Chess, 1989',                               author: 'Pandolfini',                                   box: 11 },
      { title: 'Chess Fundamentals, 1949',                             author: 'Capablanca',                                   box: 11 },
      { title: 'The 1000 Best Short Games of Chess, 1955',             author: 'Chernev',                                      box: 11 },
      { title: 'Modern Ideas in the Chess Openings, 1953',             author: 'Horowitz',                                     box: 11 },
      { title: "Queen's Gambit Declined: Tchigorin Defense, 1972",     author: 'Soltis',                                       box: 11 },
      { title: 'Development of a Grandmaster, 1991',                   author: 'Adams',                                        box: 11 },
      { title: 'Modern Chess Brilliancies, 1994',                      author: 'Evans',                                        box: 11 },
      { title: 'Improve Your Middlegame Play, 2000',                   author: 'Kinsman',                                      box: 11 },
      { title: 'Fire on Board, 1997',                                  author: 'Shirov',                                       box: 11 },
      { title: 'Chess Marches On, 1945',                               author: 'Fine',                                         box: 11 },
      { title: 'The Modern Defense, 1979',                             author: 'Hort',                                         box: 11 },
      { title: 'French Defense Tarrasch Variation, 1980',              author: 'Richmond',                                     box: 11 },
      { title: 'Hypermodern Chess, 1948',                              author: 'Reinfeld',                                     box: 11 },
      { title: 'Budapest Gambit, 1986',                                author: 'Borik',                                        box: 11 },
      { title: "Lasker's Defense to the Queen's Gambit, 1993",         author: 'Soltis',                                       box: 11 },
      { title: 'Winning Chess Tactics Illustrated, 1963',              author: 'Horowitz',                                     box: 11 },
      { title: 'The Art of Chess Analysis, 1997',                      author: 'Timman',                                       box: 11 },
      { title: "Queens Gambit Accepted Trends, 1991",                  author: 'Martin',                                       box: 11 },
      { title: 'Solitaire Chess, 1962',                                author: 'Horowitz',                                     box: 11 },
      { title: 'Practical Chess Endings, 1961',                        author: 'Chernev',                                      box: 11 },
      { title: 'How to Play Winning Chess, 1962',                      author: 'Reinfeld',                                     box: 11 },
      { title: "Reshevsky's Best Games of Chess, 1948",                author: 'Reshevsky',                                    box: 11 },
      { title: 'Computer Chess Reports, 1986',                         author: 'Sostack (ed.)',                                 box: 11 },
      { title: 'Test Your Chess, 1964',                                author: 'Abrahams',                                     box: 11 },
      { title: 'Colle Plays the Colle System, 2002',                   author: 'Harvey',                                       box: 11 },
      { title: 'Colle System Zukertort Variation 5.b3, 1998',          author: 'Soltis',                                       box: 11 },
      { title: 'Ultimate Colle, 2001',                                 author: 'Lane',                                         box: 11 },
      { title: 'Chess Openings for Black, Explained, 2005',            author: 'Alburt, Dzindzihashvilli, Perelshtyen',         box: 11 },
      { title: 'Chess Trick and Treat, 1965',                          author: 'Reubens',                                      box: 11 },
      { title: "Tarrasch's Best Games of Chess, 1960",                 author: 'Reinfeld',                                     box: 11 },
      { title: 'Budapest Gambit, 2009',                                author: 'Taylor',                                       box: 11 },
      { title: 'Budapest Defense and the Tennison Gambit, 1982',       author: 'Staker',                                       box: 11 },
      { title: 'Keres Best Games of Chess 1931-1948, 1960',            author: 'Reinfeld',                                     box: 11 },
      { title: "Lasker's Manual of Chess, 1947",                       author: 'Lasker',                                       box: 11 },
      { title: 'A Primer of Chess, 1963',                              author: 'Capablanca',                                   box: 11 },
      { title: 'Golden Treasury of Chess, 1943',                       author: 'Wellmuth',                                     box: 11 },
      { title: 'The Most Instructive Games of Chess Ever Played, 1965',author: 'Chernev',                                      box: 11 },
      { title: 'A Guide to Chess Openings, 1957',                      author: 'Barden',                                       box: 11 },
      { title: 'The Two Knights Defense, 2003',                        author: 'Pinski',                                       box: 9  },
      { title: "Italian Game and Evan's Gambit, 2005",                 author: 'Pinski',                                       box: 9  },
      { title: 'Play the Grunfeld, 2007',                              author: 'Dembo',                                        box: 9  },
      { title: 'Winning the Won Game, 2004',                           author: 'Kopec & Ftacnik',                              box: 9  },
      { title: 'Paul Morphy and the Evolution of Chess Theory, 1993',  author: 'Shibut',                                       box: 9  },
      { title: 'Chess Master vs Chess Amateur, 1963',                  author: 'Euwe & Meiden',                                box: 9  },
      { title: 'The Most Instructive Games of Young Grandmasters, 1999',author: 'Motwani',                                     box: 9  },
      { title: 'The Quickest Chess Victories of All Time, 1998',       author: 'Burgess',                                      box: 9  },
      { title: 'Modern Chess Miniatures, 1960',                        author: 'Barden & Heldenfeld',                          box: 9  },
      { title: 'Endgame Challenge, 1995',                              author: 'Hall',                                         box: 9  },
      { title: 'Knight Moves, 1998',                                   author: 'Alexander',                                    box: 9  },
      { title: 'Practical Endgame Play — Mastering the Basics, 2008',  author: 'Grivas',                                       box: 9  },
      { title: 'A Guide to Chess Improvement, 2010',                   author: 'Heisman',                                      box: 9  },
    ],
  },
  {
    name: 'Openings',
    books: [
      { title: 'Albin Countergambit, How to Play the, 1991',           author: 'Eric Schiller',                                box: 2 },
      { title: 'Albin Counter-Gambit, 1983',                           author: 'Paul Lamford',                                 box: 2 },
      { title: 'Anti-Dutch, The Contemporary, 1990',                   author: 'Andrew Martin',                                box: 2 },
      { title: 'Batsford Chess Openings 2, 1989',                      author: 'Kasparov & Keene',                             box: 6 },
      { title: 'Benoni, Guide to the Modern, 2001',                    author: 'John Watson',                                  box: 2 },
      { title: "Bishop's Opening, Winning with the, 1993",             author: 'Gary Lane',                                    box: 2 },
      { title: 'Black Defense System for the Rest of your Chess Career, A, 1987', author: 'Andrew Soltis',                    box: 2 },
      { title: 'Black Defense System With 1.d6, A, 1994',              author: 'Andrew Soltis',                                box: 2 },
      { title: 'Bogo-Indian, Play the, 1985',                          author: 'S. Taulbut',                                   box: 7 },
      { title: 'Budapest Gambit, The Fighting Fajarowicz, 1996',       author: 'Tim Harding',                                  box: 2 },
      { title: 'Budapest for the Tournament Player, The, 1992',        author: 'Tseitlin & Glaskov',                           box: 2 },
      { title: 'Cambridge Springs Defense, 1984',                      author: 'Eric Schiller',                                box: 2 },
      { title: 'Caro-Kann Defense, Winning with the, 1993',            author: 'Jeremy Silman',                                box: 2 },
      { title: 'Caro-Kann Defense Knight Variation 4.Nf6 (B15-16), 1992', author: 'Sergio Curtacci',                          box: 2 },
      { title: 'Caro-Kann Defense, New Ideas in the, 1992',            author: 'Jon Speelman',                                 box: 2 },
      { title: 'Caro-Kann, Play the, 1991',                            author: 'Egon Varnusz',                                 box: 2 },
      { title: 'Caro-Kann Defence, 1988',                              author: 'Alexei Suetin',                                box: 2 },
      { title: 'Caro-Kann Classical 4.Bf5, 1984',                      author: 'Kasparov & Shakarov',                          box: 2 },
      { title: 'Center Counter Defense: The Portuguese Variation, 1997',author: 'Selby Anderson',                              box: 2 },
      { title: 'Center Counter 1.e4 d5, Winning with the, 1991',       author: 'Ken Smith & John Hall',                        box: 2 },
      { title: 'Chess Opening for You, The, 1975',                     author: 'Larry Evans',                                  box: 7 },
      { title: 'Chess Openings: Theory and Practice, 1964',            author: 'I.A. Horowitz',                                box: 6 },
      { title: 'Chess Tutor, The: Opening Moves, 1976',                author: 'Schwob & Kane',                                box: 7 },
      { title: "Complete Defence to 1.d4, A, 1981",                    author: 'Cafferty & Hooper',                            box: 7 },
      { title: "Complete Defence to 1.P-K4, A, 1979",                  author: 'Cafferty & Hooper',                            box: 7 },
      { title: 'Dragon: Classical and Levenfish Variations, Sicilian, 1990', author: 'Sapi & Schneider',                       box: 2 },
      { title: 'Dragon: Yugoslav 9.Bc4, Sicilian, 1989',               author: 'Sapi & Schneider',                             box: 2 },
      { title: 'Dragon, Winning with the, 1994',                       author: 'Chris Ward',                                   box: 2 },
      { title: 'Dragons, Accelerated Sicilian, 1975',                  author: 'D.N.L. Levy',                                  box: 2 },
      { title: 'Dutch for the Attacking Player, The, 1996',            author: 'Steffen Pedersen',                             box: 2 },
      { title: 'Dutch Defence Leningrad Variation 7.Nc6, 1994',        author: 'Massimo Luccion',                              box: 2 },
      { title: 'Dutch Defense Against 1.c4 and 1.Nf3, Play the, 1993', author: 'DeVault & Hickman',                           box: 2 },
      { title: 'Dutch 7.Qe8, Leningrad, Winning with the, 1993',       author: 'Andrew Soltis',                                box: 2 },
      { title: 'Dutch Defense, 1989',                                  author: 'Christiansen & Silman',                        box: 2 },
      { title: 'Dutch, The Leningrad, 1976',                           author: 'T.D. Harding',                                 box: 2 },
      { title: 'Encyclopedia of Chess Openings A, 1979',               author: 'FIDE',                                         box: 6 },
      { title: 'Encyclopedia of Chess Openings A 86-89 Dutch, 1994',   author: 'FIDE',                                         box: 6 },
      { title: 'Encyclopedia of Chess Openings B, 1984',               author: 'FIDE',                                         box: 6 },
      { title: 'Encyclopedia of Chess Openings C, 1974',               author: 'FIDE',                                         box: 6 },
      { title: 'Encyclopedia of Chess Openings C 82 Ruy Lopez, 1994',  author: 'FIDE',                                         box: 6 },
      { title: 'Encyclopedia of Chess Openings D, 1976',               author: 'FIDE',                                         box: 6 },
      { title: 'Encyclopedia of Chess Openings E, 1978',               author: 'FIDE',                                         box: 6 },
      { title: 'English Defense, 1999',                                author: 'Daniel King',                                  box: 2 },
      { title: 'English Defense, Winning with the, 1994',              author: 'Andrew Soltis',                                box: 2 },
      { title: 'English Defense — e6, b6, Bb7, The, 1987',             author: 'Keene, Plaskett & Tisdall',                    box: 2 },
      { title: 'The English Opening, 2009',                            author: 'Mihail Marin',                                 box: 9 },
      { title: "Evans Gambit & System vs. Two Knights' Defense, 1991", author: 'Tim Harding',                                  box: 2 },
      { title: 'Evolution of Chess Opening Theory, The, 1985',         author: 'Raymond Keene',                                box: 7 },
      { title: 'Fischer-Sozin Attack, Winning with the, 1994',         author: 'Gary Lane',                                    box: 2 },
      { title: 'French Defence, How to Play the, 1983',                author: 'Shaun Taulbut',                                box: 7 },
      { title: 'French, Play the, 1984',                               author: 'John W. Watson',                               box: 2 },
      { title: 'French: Classical Lines, 1979',                        author: 'Harding & Heidenfeld',                         box: 2 },
      { title: 'Giuoco Piano & the Max Lange Attack, Winning with the, 1992', author: 'Andrew Soltis',                        box: 2 },
      { title: 'Grand Prix Attack: f4 Against the Sicilian, 1985',     author: 'Hodgson & Day',                                box: 2 },
      { title: 'Grand Prix Attack, Attacking the Sicilian Defense with 2.f4, 1995', author: 'Smith & Hall',                   box: 2 },
      { title: 'Grunfeld, Winning with the, 1987',                     author: 'Adorjan & Dory',                               box: 2 },
      { title: 'Grunfeld Defense, The, 1971',                          author: 'William R. Hartston',                          box: 2 },
      { title: 'Grenfeld, Beating the, 1992',                          author: 'Anatoly Karpov',                               box: 2 },
      { title: 'Hanning Schara Gambit, 1995',                          author: 'Smith & Hall',                                 box: 2 },
      { title: 'How to Play Good Opening Moves, 1982',                 author: 'Edmar Mednis',                                 box: 7 },
      { title: 'Ideas Behind The Chess Openings, 1949',                author: 'Reuben Fine',                                  box: 8 },
      { title: 'Italian Game, The, 1977',                              author: 'Harding & Botterill',                          box: 2 },
      { title: 'Kalashnikov, Winning with the, 1995',                  author: 'Neil McDonald',                                box: 2 },
      { title: "Kasparov's Opening Repertoire, 1990",                  author: 'Schiller & Shamkovich',                        box: 2 },
      { title: 'Keres Defence 1.d4 d5, 2.c4 Bf5, 1992',               author: 'Giovanni Falchetta',                           box: 2 },
      { title: 'Kings Gambit as White, The, 1984',                     author: 'Christiansen, Maser & Raingruber',             box: 2 },
      { title: 'Kings Gambit, The, 1975',                              author: 'Korchnoi & Zak',                               box: 2 },
      { title: "King's Indian Attack, 1988",                           author: 'Smith & Hall',                                 box: 7 },
      { title: "King's Indian Attack, The, 1993",                      author: 'Henley & Maddox',                              box: 2 },
      { title: "King's Indian Defense",                                author: 'A. Vetkov',                                    box: 2 },
      { title: "King's Indian, The Classical, 1990",                   author: 'John Nunn',                                    box: 2 },
      { title: 'KILL K.I.D. (four pawns attack), 2009',                author: 'Semko Semkov',                                 box: 9 },
      { title: 'Kings Indian, The Fianchetto, 1996',                   author: 'Colin McNab',                                  box: 9 },
      { title: 'Marshall Attack, The, 1974',                           author: 'Wade & Harding',                               box: 7 },
      { title: 'Modern Chess Openings 11th Edition, 1972',             author: 'Walter Korn',                                  box: 7 },
      { title: 'Modern Chess Openings, 13th Edition, 1990',            author: 'Nick De Firmian',                              box: 6 },
      { title: 'Modern Chess Openings Traps, 1972',                    author: 'William Lombardy',                             box: 7 },
      { title: 'Najdorf, Winning with the, 1993',                      author: 'Daniel King',                                  box: 3 },
      { title: 'Nimzo-Indian Defense, New Ideas in the, 1994',         author: 'Tony Kosten',                                  box: 2 },
      { title: 'Nimzo-Indian Defence, Play the, 1985',                 author: 'Svetozar Gligoric',                            box: 2 },
      { title: 'Nimzo Indian, Play the 4.f3, 2009',                    author: 'Yuri Yakovich',                                box: 9 },
      { title: 'Nimzovich Attack: The Norfolk Gambits, 1997',          author: 'Claude F. Bloodgood',                          box: 2 },
      { title: 'Nimzo-Larsen Attack, 2001',                            author: 'Jacobs & Tait',                                box: 2 },
      { title: 'Nimzowitsch/Larsen Attack, 1977',                      author: 'Raymond Keene',                                box: 2 },
      { title: 'Opening Ideas and Analysis for Advanced Players, 1992',author: 'Andrew Soltis',                                box: 2 },
      { title: 'Orangutan, The, 1989',                                 author: 'Bill Wall',                                    box: 2 },
      { title: 'Penguin Book of Chess Openings, The, 1981',            author: 'W.R. Hartston',                                box: 7 },
      { title: 'Petroff Defense Cochrane Gambit, 1994',                author: 'W. John Lutes',                                box: 2 },
      { title: 'Petroff, Winning with the, 1993',                      author: 'Anatoly Karpov',                               box: 3 },
      { title: 'Philidor Counter-Gambit, The Dynamic, 1996',           author: 'James R. West',                                box: 3 },
      { title: 'Philidor Countergambit, The, 1994',                    author: 'James R. West',                                box: 3 },
      { title: 'Pirc Defence, New Ideas in the, 1993',                 author: 'John Nunn',                                    box: 3 },
      { title: 'Pirc, The Complete, 1989',                             author: 'John Nunn',                                    box: 3 },
      { title: 'Ponziani Opening, The Modern, 1993',                   author: 'Salome & Bickford',                            box: 3 },
      { title: 'Ponziani Opening, 1984',                               author: 'T.D. Harding',                                 box: 3 },
      { title: 'Practical Chess Openings, 1948',                       author: 'Reuben Fine',                                  box: 8 },
      { title: "Queen's Gambit Accepted, New Ideas in the, 1994",      author: 'Glenn Flear',                                  box: 3 },
      { title: "Queen's Gambit Declined, 1974",                        author: 'Sergiu Samarian',                              box: 3 },
      { title: "Queen's Indian, Winning with the, 1987",               author: 'Ribli & Kallair',                              box: 3 },
      { title: 'Queen Pawn Openings, Complete Defense to, 1998',       author: 'Eric Schiller',                                box: 3 },
      { title: 'Richter-Veresov the Chameleon Chess Repertoire, 1999', author: 'Stetsko & Gufeld',                             box: 3 },
      { title: 'Ruy Lopez, Arkhangelsk System, 1987',                  author: 'Jerzy Konikowski',                             box: 3 },
      { title: 'Scandinavian Defense, Anderssen Counter Attack, 1988', author: 'W. John Lutes',                                box: 3 },
      { title: 'Scotch Game, The, 1998',                               author: 'Peter Wells',                                  box: 3 },
      { title: 'Semi-Slav, the Botvinnik (and Moscow Variation), 2000',author: 'Steffen Pedersen',                             box: 3 },
      { title: 'Semi-Slav, The Complete, 1994',                        author: 'Peter Wells',                                  box: 3 },
      { title: 'Sveshnikov Reloaded, The, 2005',                       author: 'Dorian Rogozenko',                             box: 1 },
      { title: 'Sicilian Defense Chameleon Variation, Beating The, 1990', author: 'Andrew Soltis',                            box: 3 },
      { title: 'Sicilian: Keres Attack, 1981',                         author: 'Jon Kinlay',                                   box: 3 },
      { title: 'Sicilian: Lasker-Pelikan, 1978',                       author: 'Speelman, Povah & Backstock',                  box: 3 },
      { title: 'Sicilian Pelikan, The, 1989',                          author: 'Sveshnikov',                                   box: 7 },
      { title: 'Sicilian Richter-Rauzer, The, 1975',                   author: 'Harding & Markland',                           box: 7 },
      { title: 'Sicilian Sozin, The, 1974',                            author: 'Harding, Botterill & Kottnauer',               box: 3 },
      { title: 'Sicilian, New Ideas in the Sveshnikov, 1996',          author: 'Neverov & Marusenko',                          box: 3 },
      { title: 'Sicilian Defense, How to Play the, 1987',              author: "Levy & O'Connell",                             box: 3 },
      { title: 'Slav, Winning with the, 1994',                         author: 'Markov & Schipkov',                            box: 3 },
      { title: 'Slav for the Tournament Player, The, 1988',            author: 'Glenn Flear',                                  box: 3 },
      { title: 'Smith-Morra Gambit, Winning with the, 1994',           author: 'Graham Burgess',                               box: 3 },
      { title: 'Sokolsky Opening with 1.b4 e5, The Modern, 1993',      author: 'Salome & Bickford',                            box: 3 },
      { title: 'Spanish, Winning with the, 1994',                      author: 'Anatoly Karpov',                               box: 3 },
      { title: 'St. George, The New, 1993',                            author: 'Michael Basman',                               box: 3 },
      { title: 'Starting Out: The French, 2002',                       author: 'Bryon Jacobs',                                 box: 3 },
      { title: "Starting Out: The King's Indian, 2002",                author: 'Joe Gallagher',                                box: 3 },
      { title: 'Starting Out: The Pirc/Modern, 2002',                  author: 'Joe Gallagher',                                box: 3 },
      { title: 'Starting Out: The Ruy Lopez, 2003',                    author: 'John Shaw',                                    box: 3 },
      { title: 'Starting Out: The Sicilian, 2002',                     author: 'John Emms',                                    box: 3 },
      { title: 'Sveshnikov Sicilian, 1996',                            author: 'Mikhail Krasenkov',                            box: 3 },
      { title: 'Tennison Gambit 1.Nf3 d5, 2.e4, 1995',                author: 'John Lutes',                                   box: 3 },
      { title: 'Torre Attack, Winning with the, 1993',                 author: 'Gufeld & Stetsko',                             box: 3 },
      { title: 'Torre Attack, How to Play the, 1991',                  author: 'Eric Schiller',                                box: 3 },
      { title: 'Two Knights Defence, The, 1983',                       author: 'Yakov Estrin',                                 box: 3 },
      { title: 'Van Geet Opening 1.Nc3, 1994',                         author: 'D.D. van Geet',                                box: 3 },
      { title: 'Vienna Game and Gambit, 1992',                         author: 'Santasiere & Smith',                           box: 3 },
      { title: 'Vienna Opening, 1976',                                 author: 'T.D. Harding',                                 box: 3 },
      { title: 'Von Hennig-Schara Gambit, 1992',                       author: 'Eric Schiller',                                box: 3 },
      { title: 'Vulture & Associated Opening Systems, The, 1989',      author: 'Stefan Bucker',                                box: 3 },
      { title: 'White Opening System Combining Stonewall Attack, Colle System, and Torre Attack, 1992', author: 'Andrew Soltis', box: 3 },
      { title: 'White Repertoire after 1.e4 e5, 2.Nf3, An Unbeatable, 1988', author: 'Evans & Smith',                        box: 3 },
      { title: 'Winning Chess Openings, 1973',                         author: 'Fred Reinfeld',                                box: 8 },
    ],
  },
  {
    name: 'Endgames',
    books: [
      { title: 'Basic Chess Endings, 2003',                            author: 'Reuben Fine',                                  box: 4 },
      { title: 'Domination in 2,545 Endgame Studies, 1974',            author: 'Kasparyan',                                    box: 7 },
      { title: "Dvoretsky's Endgame Manual 2nd ed., 2006",             author: 'Mark Dvoretsky',                               box: 9 },
      { title: 'Endgame Artillery: Queen & Rook Endings, 1982',        author: 'Alex Angos',                                   box: 7 },
      { title: 'Fundamental Chess Endings, 2002',                      author: 'Lamprecht & Muller',                           box: 9 },
      { title: 'Guide to Chess Endings, A, 1979',                      author: 'Euwe & Hooper',                                box: 4 },
      { title: 'How to Play the Endgame in Chess, 1975',               author: 'Leonard Barden',                               box: 4 },
      { title: 'How to Win in the Chess Endings, 1973',                author: 'I.A. Horowitz',                                box: 4 },
      { title: 'Minor-Piece Endings, Secrets of, 1995',                author: 'John Nunn',                                    box: 4 },
      { title: 'Pawn Endings, Secrets of, 2000',                       author: 'Muller & Lamprecht',                           box: 4 },
      { title: 'Practical Chess Endings, 1974',                        author: 'Paul Keres',                                   box: 4 },
      { title: 'Rook Endings, Secrets of, 1999',                       author: 'John Nunn',                                    box: 4 },
      { title: 'Tactical Chess Endings, 1981',                         author: 'John Nunn',                                    box: 7 },
    ],
  },
  {
    name: 'Matches',
    books: [
      { title: 'Fischer vs. Spassky, 1972',                            author: 'Roberts, Schonberg, Horowitz & Reshevsky',     box: 3 },
      { title: "Fischer vs. Spassky, The Chess Match of the Century, 1972", author: 'Svetozar Gligoric',                      box: 3 },
      { title: 'Fischer-Spassky 1992 Rematch, 1993',                   author: 'Shmkovich & Cartier',                          box: 7 },
      { title: 'Karpov vs. Kasparov II, Maneuvers in Moscow, 1985',    author: 'Keene & Goodman',                              box: 3 },
      { title: 'New World Chess Champion: Karpov-Kasparov, 1986',      author: 'Garry Kasparov',                               box: 7 },
      { title: 'Karpov-Kasparov 1990, 1991',                           author: 'Maddox & Henley',                              box: 7 },
      { title: 'Kasparov-Korchnoi: The London Contest, 1983',          author: 'Keene & Lawson',                               box: 7 },
      { title: 'Korchnoi vs. Karpov, The World Chess Championship, 1978', author: 'Raymond Keene',                             box: 3 },
      { title: 'Persona Non Grata, 1981',                              author: 'Kortchnoi',                                    box: 7 },
      { title: 'Tal Botvinnik 1960',                                   author: 'Mikhail Tal',                                  box: 3 },
    ],
  },
  {
    name: 'Puzzles & Problems',
    books: [
      { title: '101 Questions on How to Play Chess, 1994',             author: 'Fred Wilson',                                  box: 7 },
      { title: '200 Perplexing Chess Puzzles, 1997',                   author: 'Martin Greif',                                 box: 4 },
      { title: '1001 Winning Chess Sacrifices and Combinations, 1955', author: 'Fred Reinfield',                               box: 7 },
      { title: 'Bobby Fischer Teaches Chess, 1966',                    author: 'Bobby Fischer',                                box: 7 },
      { title: 'Chess 5334 Problems, Combination and Games, 1994',     author: 'Laszio Polgar',                                box: 4 },
      { title: "It's Your Move, 1976",                                 author: 'Teschner & Miles',                             box: 7 },
      { title: 'Looking for Trouble, 2003',                            author: 'Dan Heisman',                                  box: 4 },
      { title: "What's the Best Move?, 1973",                          author: 'Larry Evans',                                  box: 4 },
      { title: 'Winning Chess, How to See Three Moves Ahead, 1948',    author: 'Chernev & Reinfeld',                           box: 4 },
    ],
  },
  {
    name: 'Tournaments',
    books: [
      { title: '22nd U.S.S.R. Chess Championship',                     author: 'H. Golombek',                                  box: 4 },
      { title: '15th World Student Team Chess Championship 1968',      author: 'Jaroslav Sajtar',                              box: 4 },
      { title: '40th U.S.S.R. Final, Baku, 1972',                     author: '',                                             box: 4 },
      { title: 'Alekhine Memorial Tournament, Moscow 1971',            author: '',                                             box: 4 },
      { title: 'First Piatigorsky Cup, Los Angeles 1963 (1965)',       author: 'Isaac Kashdan',                                box: 4 },
      { title: 'Games of the 1993 U.S. Women\'s Championship',         author: 'Terese Hatch & David Hatch',                   box: 4 },
      { title: 'Great Chess Tournaments & Their Stories, The, 1975',   author: 'Andy Soltis',                                  box: 7 },
      { title: 'Leningrad Interzonal 1973',                            author: '',                                             box: 4 },
      { title: 'London 1980 (1981)',                                   author: 'Hartston & Reuben',                            box: 4 },
      { title: 'Lone Pine, The Best of, 1981',                         author: 'Grefe & Waterman',                             box: 7 },
      { title: 'Maroczy Memorial Tournament, Budapest 1952',           author: 'H. Golombek',                                  box: 4 },
      { title: 'New York International Chess Tournament, 1961',        author: 'Helms & Alekhine',                             box: 8 },
      { title: 'San Francisco 1995, Grandmaster Invitational',         author: 'James Eade',                                   box: 4 },
      { title: 'Sousse 1967 (1968)',                                   author: 'R.G. Wade',                                    box: 4 },
      { title: 'Tallin International Chess Tournament, 1973',          author: '',                                             box: 4 },
      { title: 'Wijk aan Zee Grandmaster Chess Tournament 1975, 1976', author: 'By the Players',                               box: 7 },
      { title: 'World Chess Championship, The, 1972',                  author: 'R.G. Wade',                                    box: 4 },
      { title: 'Zurich International Chess Tournament 1953 (1979)',    author: 'David Bronstein',                              box: 4 },
    ],
  },
  {
    name: 'Great Players & Their Games',
    books: [
      { title: 'Alexander Alekhine, 1975',                             author: 'Alexander Kotov',                              box: 4 },
      { title: 'Alexander Alekhine, My Best Games of Chess 1908-1937 (1985)', author: 'Alexander Alekhine',                   box: 4 },
      { title: 'Anatoly Karpov, The Games of, 1974',                   author: "Adams & O'Connell",                            box: 7 },
      { title: "Karpov's Collected Games 1961-1974, 1975",             author: 'David Levy',                                   box: 7 },
      { title: 'Application of Chess Theory, The, 1984',               author: 'Y.P. Geller',                                  box: 7 },
      { title: 'Best Chess Games 1970-80, 1982',                       author: 'Jon Speelman',                                 box: 8 },
      { title: 'Bisguier, The Art of, 2003',                           author: 'Arthur B. Bisquier & Newton Berry',            box: 1 },
      { title: 'Bobby Fischer, How to Beat, 1974',                     author: 'Edmar Mednis',                                 box: 7 },
      { title: 'Bobby Fischer, The Chess of, 1975',                    author: 'Robert Burger',                                box: 7 },
      { title: 'Bobby Fischer, Complete Games of the American World Chess Champion, 1995', author: 'Lou Hays',                box: 4 },
      { title: 'Bobby Fischer: Profile of a Prodigy, 1965',            author: 'Frank Brady',                                  box: 7 },
      { title: "Capablanca's 100 Best Games of Chess",                  author: 'H. Golombek',                                  box: 4 },
      { title: 'Chess Champion, The, 1973',                            author: 'Frederick Edge',                               box: 7 },
      { title: "Chess Praxis: The Praxis of My System, 1936",          author: 'A. Nimzovich',                                 box: 7 },
      { title: 'David Lees, The Chess Games of, 1992',                 author: 'David Lees',                                   box: 1 },
      { title: 'Emanuel Lasker: The Life of a Chess Master, 1991',     author: 'Dr. J. Hannak',                                box: 4 },
      { title: 'Garry Kasparov on Modern Chess Part 2, 2008',          author: 'Garry Kasparov',                               box: 1 },
      { title: "Garry Kasparov's Greatest Games, Volume 1, 2005",      author: 'Igor Stohl',                                   box: 1 },
      { title: 'Search for Chess Perfection: C.J.S. Purdy, 1997',      author: 'C.J.S. Purdy',                                 box: 4 },
      { title: 'Kramnik: My Life and Games, 2000',                     author: 'Kramnik & Damsky',                             box: 1 },
      { title: 'My 60 Memorable Games, 1969',                          author: 'Bobby Fischer',                                box: 7 },
      { title: 'My Best Games of Chess 1908-1923, 1927',               author: 'A. Alekhine',                                  box: 7 },
      { title: 'My Best Games of Chess 1935-1957, 1958',               author: 'V.V. Smyslov',                                 box: 7 },
      { title: 'One Hundred Selected Games, 1960',                     author: 'Botvinnik',                                    box: 7 },
      { title: 'Paul Keres, The Complete Games of, 1977',              author: 'Paul Keres',                                   box: 7 },
      { title: 'Paul Morphy, The Exploits & Triumphs in Europe of',    author: '',                                             box: 7 },
      { title: 'Paul Morphy, 1976',                                    author: 'David Lawson',                                 box: 7 },
      { title: 'Morphy, The Unknown: Games Writings, Biography, 1973', author: 'Philip Sergeant',                              box: 7 },
      { title: 'Polgar Sisters, The, 1992',                            author: 'Cathy Forbes',                                 box: 7 },
      { title: "Reti's Best Games of Chess, 1974",                     author: 'Reti & Golombek',                              box: 7 },
      { title: "Rubinstein's Chess Masterpieces, 1941",                author: 'Hans Kmoch',                                   box: 1 },
      { title: "Viktor Korchnoi's Best Games, 1977",                   author: 'Viktor Korchnoi',                              box: 7 },
    ],
  },
  {
    name: 'Strategy, Tactics & Middlegame',
    books: [
      { title: '200 Miniature Games of Chess, 1965',                   author: 'J. du Mont',                                   box: 8 },
      { title: '500 Master Games of Chess, 1975',                      author: 'Tartakower & Du Mont',                         box: 5 },
      { title: 'Analyse to Win, Visualising Victory, 1997',            author: 'Byron Jacobs',                                 box: 5 },
      { title: 'Art of Attack in Chess, 1998',                         author: 'V. Vukovic',                                   box: 5 },
      { title: 'Art of Defense in Chess, The, 1975',                   author: 'Andrew Soltis',                                box: 8 },
      { title: 'Art of Sacrifice in Chess, The, 1951',                 author: 'Rudolf Spielmann',                             box: 8 },
      { title: 'Art of the Checkmate, The, 1953',                      author: 'Renaud & Kahn',                                box: 8 },
      { title: 'Attack and Defence in Modern Chess Tactics, 1973',     author: 'Ludek Pachman',                                box: 5 },
      { title: 'Attacking Technique, 1996',                            author: 'Colin Crouch',                                 box: 5 },
      { title: 'Batsford Chess Yearbook, The, 1975',                   author: "Kevin O'Connell",                              box: 8 },
      { title: 'Boost Your Chess 2, 2010',                             author: 'Artur Yusupov',                                box: 9 },
      { title: 'Catalog of Chess Mistakes, 1979',                      author: 'Andrew Soltis',                                box: 8 },
      { title: 'Championship Chess, 1963',                             author: 'P.W. Sergeant',                                box: 8 },
      { title: 'Chess Catechism, 1970',                                author: 'Larry Evans',                                  box: 8 },
      { title: 'Chess for Fun & Chess for Blood, 1962',                author: 'Edward Lasker',                                box: 8 },
      { title: 'Chess Instructions: Move By Move, 1984',               author: 'Chess Digest',                                 box: 8 },
      { title: 'Chess Secrets I Learned from the Masters, 1969',       author: 'Edward Lasker',                                box: 8 },
      { title: 'Chess Strategy, 1976',                                 author: 'Fred Reinfeld',                                box: 8 },
      { title: 'Chess: Tactics and Strategy, 1997',                    author: 'Graham Burgess',                               box: 5 },
      { title: 'Chess: Tactics for Advanced Players, 1992',            author: 'Yuri Averbakh',                                box: 5 },
      { title: 'Chess Traps, Pitfalls & Swindles, 1954',               author: 'Horowitz & Reinfeld',                          box: 8 },
      { title: 'Chess for Tigers, 1990',                               author: 'Simon Webb',                                   box: 5 },
      { title: 'Chess Middlegames: Essential Knowledge, 1996',         author: 'Yuri Averbakh',                                box: 5 },
      { title: 'Combinations, The Heart of Chess, 1960',               author: 'Irving Cherney',                               box: 5 },
      { title: 'Combinations, Winning Chess Series, 2006',             author: 'Yasser Seirawan',                              box: 5 },
      { title: 'Common Sense in Chess, 1965',                          author: 'Emanuel Lasker',                               box: 8 },
      { title: 'The Complete Chess Course, 1953',                      author: 'Fred Reinfeld',                                box: 8 },
      { title: 'Complete Chess Player, The, 1953',                     author: 'Fred Reinfeld',                                box: 5 },
      { title: 'Complete Chess Strategy: Play on the Wings, 1978',     author: 'Ludek Pachman',                                box: 5 },
      { title: 'Complete Chess Strategy: Volume 2 — Pawn Play and the Center, 1978', author: 'Pachman',                       box: 8 },
      { title: 'Dynamic Chess Strategy, 2010',                         author: 'Mihai Suba',                                   box: 9 },
      { title: 'Elements of Positional Evaluation 4th Edition, 2010',  author: 'Dan Heisman',                                  box: 9 },
      { title: 'Encyclopedia of Chess Middlegames: Combinations, 1980',author: 'Chess Informant',                              box: 5 },
      { title: 'Essential GM Chess Knowledge (GM-RAM), 2000',          author: 'Ziyatdinov & Dyson',                           box: 1 },
      { title: 'Evans on Chess, 1974',                                 author: 'Larry Evans',                                  box: 8 },
      { title: 'Fire on Board Part II: 1997-2004, 2005',               author: 'Alexei Shirov',                                box: 1 },
      { title: 'Fireside Book of Chess, The, 1949',                    author: 'Chernev & Reinfield',                          box: 8 },
      { title: 'Game of Chess, The, 1977',                             author: 'Tarrasch',                                     box: 8 },
      { title: 'Garry Kasparov on My Great Predecessors: Part I, 2003',author: 'Garry Kasparov',                               box: 1 },
      { title: 'Garry Kasparov on My Great Predecessors: Part II, 2003',author: 'Garry Kasparov',                              box: 1 },
      { title: 'Garry Kasparov on Fischer My Great Predecessors: Part IV, 2004', author: 'Garry Kasparov',                    box: 1 },
      { title: 'Golden Dozen, The, 1976',                              author: 'Irving Chernev',                               box: 8 },
      { title: 'Great Chess Victories and Defeats, 1990',              author: 'Robert Byrne',                                 box: 5 },
      { title: 'How to Beat the Russians, 1978',                       author: 'Edmar Mednis',                                 box: 8 },
      { title: 'How to Play the Middle Game in Chess, 1974',           author: 'John Littlewood',                              box: 8 },
      { title: 'Inner Game of Chess: How to Calculate and Win, 1994',  author: 'Andrew Soltis',                                box: 5 },
      { title: 'Journal of a Chess Original, 1996',                    author: 'Stephan Gerzadowicz',                          box: 5 },
      { title: 'Judgment and Planning in Chess, 1979',                 author: 'Max Euwe',                                     box: 8 },
      { title: 'King Power in Chess, 1982',                            author: 'Edmar Mednis',                                 box: 8 },
      { title: 'Learn Chess from the World Champions, 1979',           author: 'David Levy',                                   box: 8 },
      { title: 'Mammoth Book of Chess, The, 1997',                     author: 'Graham Burgess',                               box: 5 },
      { title: 'Masters of the Chessboard, 1976',                      author: 'Richard Reti',                                 box: 8 },
      { title: 'Modern Chess Sacrifice, The, 1978',                    author: 'Shamkovich',                                   box: 8 },
      { title: 'Modern Chess Strategy, 1963',                          author: 'Ludek Pachman',                                box: 5 },
      { title: 'Modern Chess Strategy, 1973',                          author: 'Edward Lasker',                                box: 8 },
      { title: 'My System, 1975',                                      author: 'Aron Nimzovich',                               box: 5 },
      { title: 'New Traps in the Chess Opening, 1972',                 author: 'A. Horowitz',                                  box: 8 },
      { title: 'Passion For Chess, A, 1958',                           author: 'Reuben Fine',                                  box: 8 },
      { title: 'Perfect Your Chess, 2007',                             author: 'Volokitin & Grabinsky',                        box: 9 },
      { title: 'Play Like a Grandmaster, 1978',                        author: 'Alexander Kotov',                              box: 5 },
      { title: 'Point Count Chess, 1960',                              author: 'Horowitz & Mott-Smith',                        box: 5 },
      { title: 'Positional Play, 1996',                                author: 'Dvoretsky & Yusupov',                          box: 5 },
      { title: 'Principles of the New Chess, 1986',                    author: 'Bruce Pandolfini',                             box: 8 },
      { title: 'Rapid Chess Improvement, 2002',                        author: 'Michael de la Maza',                           box: 1 },
      { title: 'School of Chess Excellence 2: Tactical Play, 2002',    author: 'Ken Neat',                                     box: 5 },
      { title: 'Secrets of Grandmaster Play, 1987',                    author: 'Nunn & Griffiths',                             box: 5 },
      { title: 'Secrets of Modern Chess Strategy, 1998',               author: 'John Watson',                                  box: 5 },
      { title: 'Tactics in the Sicilian, 1993',                        author: 'Gennady Nesis',                                box: 5 },
      { title: 'Technique in Chess, 1961',                             author: 'Gerald Abrahams',                              box: 8 },
      { title: 'The Right Way to Play Chess, 1950',                    author: 'Pritchard',                                    box: 8 },
      { title: 'Think like a Grandmaster, 1995',                       author: 'Alexander Kotov',                              box: 5 },
      { title: 'Training for the Tournament Player, 1996',             author: 'Dvoretsky & Yusupov',                          box: 5 },
      { title: "World's Most Instructive Amateur Game Book, 2012",     author: 'Dan Heisman',                                  box: 9 },
    ],
  },
  {
    name: 'Chess Informant',
    books: [
      { title: 'Chess Informant 54, 1992',   author: 'FIDE', box: 6 },
      { title: 'Chess Informant 55, 1992',   author: 'FIDE', box: 6 },
      { title: 'Chess Informant 56, 1993',   author: 'FIDE', box: 6 },
      { title: 'Chess Informant 57, 1993',   author: 'FIDE', box: 6 },
      { title: 'Chess Informant 59, 1994',   author: 'FIDE', box: 6 },
      { title: 'Chess Informant 60, 1994',   author: 'FIDE', box: 6 },
      { title: 'Chess Informant 61, 1994',   author: 'FIDE', box: 6 },
      { title: 'Chess Informant 65, 1996',   author: 'FIDE', box: 6 },
      { title: 'Chess Informant 66, 1996',   author: 'FIDE', box: 6 },
      { title: 'Chess Informant 67, 1996',   author: 'FIDE', box: 6 },
      { title: 'Chess Informant 96, 2006',   author: 'FIDE', box: 9 },
      { title: 'Chess Informant 97, 2006',   author: 'FIDE', box: 9 },
      { title: 'Chess Informant 98, 2006',   author: 'FIDE', box: 9 },
      { title: 'Chess Informant 99, 2007',   author: 'FIDE', box: 9 },
      { title: 'Chess Informant 100, 2007',  author: 'FIDE', box: 9 },
      { title: 'Chess Informant 101, 2007',  author: 'FIDE', box: 9 },
      { title: 'Chess Informant 102, 2008',  author: 'FIDE', box: 9 },
      { title: 'Chess Informant 103, 2008',  author: 'FIDE', box: 9 },
    ],
  },
  {
    name: 'Miscellaneous',
    books: [
      { title: 'British Chess Masters, 1947',                          author: 'F. Reinfeld',                                  box: 4 },
      { title: 'Chess Coaching, 1991',                                 author: 'John Littlewood',                              box: 4 },
      { title: 'Chess Encyclopedia, The, 1990',                        author: 'Nathan Divinsky',                              box: 1 },
      { title: 'Chess Greats of Germany and Austria, 1994',            author: 'Newton Berry',                                 box: 4 },
      { title: 'Dragon Variation, The, 1969 (Reading Book)',           author: 'Anthony Glyn',                                 box: 8 },
      { title: "Queen's Gambit, The, 1983 (Reading Book)",             author: 'Walter Tevis',                                 box: 4 },
      { title: 'Rating of Chess Players, The, 1978',                   author: 'Arpad E. Elo',                                 box: 4 },
      { title: 'Lisa, a Chess Novel, 2013',                            author: 'Jesse Kraai',                                  box: 9 },
    ],
  },
];

const TOTAL = CATEGORIES.reduce((sum, cat) => sum + cat.books.length, 0);

export default function BookListPage() {
  const [query, setQuery] = useState('');

  const filtered = useMemo(() => {
    if (!query.trim()) return CATEGORIES;
    const q = query.toLowerCase();
    return CATEGORIES.map(cat => ({
      ...cat,
      books: cat.books.filter(
        b => b.title.toLowerCase().includes(q) || b.author.toLowerCase().includes(q)
      ),
    })).filter(cat => cat.books.length > 0);
  }, [query]);

  const resultCount = filtered.reduce((sum, cat) => sum + cat.books.length, 0);

  return (
    <div className="swcc-page-shell">
      <div className="swcc-page-banner">
        <p className="swcc-section-label">Henry R. Meifert Memorial Library</p>
        <h1 className="swcc-section-title">Chess Book List</h1>
        <p className="swcc-page-banner-sub">
          {TOTAL} titles available for 3-week checkout · See Chris Wainscott to borrow
        </p>
      </div>

      <div className="swcc-page-inner wide">
        <p style={{ fontSize: '0.85rem', color: 'var(--swcc-color-text-muted)', marginBottom: '1.5rem' }}>
          To borrow a book, fill out the{' '}
          <a
            href="http://www.southwestchessclub.com/downloads/ChessBookform.pdf"
            target="_blank" rel="noreferrer" className="swcc-text-link"
          >
            checkout form (PDF) ↓
          </a>{' '}
          and see Chris Wainscott, who will bring in your selection the following week.
          Checkout period is 3 weeks. Also see the{' '}
          <a href="/dvds" className="swcc-text-link">DVD &amp; CD list →</a>
        </p>

        <input
          type="text"
          className="swcc-book-search"
          placeholder="Search by title or author…"
          value={query}
          onChange={e => setQuery(e.target.value)}
          aria-label="Search books"
        />

        {query && (
          <p className="swcc-book-count">
            {resultCount === 0
              ? 'No books found.'
              : `${resultCount} book${resultCount !== 1 ? 's' : ''} found`}
          </p>
        )}

        {filtered.map(cat => (
          <div key={cat.name} className="swcc-book-category">
            <h2 className="swcc-book-category-title">{cat.name}</h2>
            {!query && (
              <p className="swcc-book-count">{cat.books.length} titles</p>
            )}
            <table className="swcc-book-table">
              <thead>
                <tr>
                  <th style={{ width: '50%' }}>Title</th>
                  <th>Author</th>
                  <th style={{ width: 60 }}>Box</th>
                </tr>
              </thead>
              <tbody>
                {cat.books.map((book, i) => (
                  <tr key={i}>
                    <td>{book.title}</td>
                    <td>{book.author}</td>
                    <td className="box">{book.box}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ))}
      </div>
    </div>
  );
}
